name: ipg_flutter
description: "Flutter version of Onepay internet payment gateway"
version: 1.0.0
homepage: https://github.com/onepay-srilanka/onepay-flutter-sdk

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  http: ^1.3.0
  basic_utils: ^5.6.1
  pointycastle: ^3.7.3
  convert: ^3.1.1
  device_info_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
    assets:
      - lib/resources/media/ic-shield-check.png
      - lib/resources/media/ic-amex.png
      - lib/resources/media/ic-visa.png
      - lib/resources/media/ic-master-card.png
fonts:
  - family: Inter
    fonts:
      - asset: resources/fonts/Inter-Regular.ttf
        weight: 400
      - asset: resources/fonts/Inter-Medium.ttf
        weight: 500
      - asset: resources/fonts/Inter-Bold.ttf
        weight: 700

